### ISSUE TITLE
Open-shell systems with Emin_PCG

### ISSUE THREAD

**Issue by wangenau** [f-fathurrahman/PWDFT.jl#11]
Hello,

I was playing around with your code and ran into an error. So my question is: Is it possible to calculate open-shell systems with the Emin_PCG minimization method?

I tried the following
```
using PWDFT
atoms = Atoms(xyz_file="H.xyz", LatVecs=gen_lattice_sc(10.0))
Ham = Hamiltonian(atoms, ["psp_path/H-q1.gth"], 10.0, Nspin=2)
KS_solve_Emin_PCG!(Ham, startingrhoe="random")
```
but after the second iteration the total energy will become NaN. The same happens, e.g., for lithium. It seems that this method does not work with empty states?
I know that I can use `KS_solve_SCF` and the calculation will work, but I am interested in the energy difference between both methods.

Is it somehow possible to get the calculation to work?
Thanks in advance!

**Comment by f-fathurrahman** [comment]
Hello,

Thank you for reporting this @wangenau . 

I think this problem is encountered for system with only one electron and `Nspin=2` such as `H-q1` and `Li-q1`. When I use `Li-q3` it is still fine.

The main culprit is that the gradient for spin state (up or down) with no electron becomes zeros and thus gives `NaN` for beta CG (the variable `β` in `KS_solve_Emin_PCG`). A simple fix that I found to work is to check whether beta CG is `NaN`, if it is then set the value to zero.

```julia
# .... in KS_solve_Emin_PCG.jl

if β[i] < 0.0 || isnan(β[i])
    β[i] = 0.0
end
# ....
```

Note that beta CG here is calculated only by considering only  the up or down spin (i.e. we have two value of beta CG, one for up and one for down).

Another possible fix is to use beta CG that is calculated by considering both up and down states. If I'm not mistaken it is implemented in JDFTx.

JDFTx also implements the direct KS minimization with smearing which we currently don't implement.

Please note that I do not test `KS_solve_Emin_PCG` for `Nspin=2`. Also please note that we might need to set the occupation numbers manually in `electrons.Focc` as the constructor does not implement a method to specify the spin multiplicity.

**Comment by wangenau** [comment]
Awesome, thanks for the quick help.
I played around a bit and it seems to work as I would expect. Thanks a lot!
While at it I also opened a very nit-picky PR: https://github.com/f-fathurrahman/PWDFT.jl/pull/12
